### ISSUE TITLE
Create a formula to get insights from a specific repo based on its URL (python)

### ISSUE THREAD

**Issue by GuillaumeFalourd** [GuillaumeFalourd/formulas-insights#3]
## What I would like to see

A formula (automation) following [this implementation](https://github.com/GuillaumeFalourd/formulas-insights/blob/master/github/get/my-insights/src/formula/formula.py) in python, to get insights based on a public repository URL (or a list of public repository URLs) informed by the user.

The final result could lead to something like this:

```
➜  ~ rit github specific-insights
? What repository do you want to get insights from ? https://github.com/GuillaumeFalourd/formulas-insights/
? Do you want contribution details? no
🐙 Getting insights for repository:
        - github.com/GuillaumeFalourd/formulas-insights/

-------------------------------------------------------------------------------------------------------
Repository                  Views     Uniques     Clones   Contributors   Forks      Stars     Watchers
-------------------------------------------------------------------------------------------------------
formulas-insights             88         11         14          1           0          1          1
```

**Comment by mfreyeso** [comment]
Hello! Could you assign me it?

**Comment by GuillaumeFalourd** [comment]
Sure @mfreyeso 👍 
I've assigned it to you. Thank you for contributing!

**Comment by GuillaumeFalourd** [comment]
There was a problem on the Makefiles @mfreyeso that has been resolved by the Ritchie team last week.
Old Makefiles wouldn't build successfully for every OS.
I've updated them so you can get the last version to implement without having this problem.

**Comment by mfreyeso** [comment]
Fine! thanks @GuillaumeFalourd
